apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nexus-cert
  namespace: istio-system
spec:
  secretName: nexus-tls
  commonName: nexus.${OSH_FQDN}
  dnsNames:
    - nexus.${OSH_FQDN}
  issuerRef:
    kind: ClusterIssuer
    name: cloudflare
