apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: horizon-cert
  namespace: istio-system
spec:
  secretName: horizon-tls
  commonName: horizon.${OSH_FQDN}
  dnsNames:
    - horizon.${OSH_FQDN}
  issuerRef:
    kind: ClusterIssuer
    name: cloudflare
