apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio
  namespace: istio-system
spec:
  profile: default
  values:
    global:
      jwtPolicy: third-party-jwt
      istiod:
        enableAnalysis: false
      proxy:
        autoInject: enabled
