apiVersion: v1
kind: Namespace
metadata:
  name: vault
#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: vault-approle
#  namespace: vault
#stringData:
#  secret-id: ${VAULT_SECRET_ID}
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: vault
stringData:
  token: ${VAULT_TOKEN}
---
apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: vault
spec:
  provider:
    vault:
      server: https://vault.${OSH_FQDN}
      path: secret
      version: v2
      auth:
        tokenSecretRef:
          name: vault-token
          namespace: vault
          key: token
        # appRole:
        #   path: approle
        #   roleId: ${VAULT_APPROLE_ID}
        #   secretRef:
        #     name: vault-approle
        #     namespace: vault
        #     key: secret-id
