apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: istio-system
spec:
  auth:
    strategy: "token"
  deployment:
    accessible_namespaces:
      - "**"
    view_only_mode: false
  server:
    web_root: "/"
  host_aliases:
    hostnames:
      - kiali.${OSH_FQDN}
  ingress:
    class_name: istio
    enabled: true
    override_yaml:
      spec:
        rules:
          - http:
              paths:
                path: /
  external_services:
    prometheus:
      url: http://prometheus.lens-metrics.svc.cluster.local
