apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kasten-cert
  namespace: istio-system
spec:
  secretName: kasten-tls
  commonName: kasten.${OSH_FQDN}
  dnsNames:
    - kasten.${OSH_FQDN}
  issuerRef:
    kind: ClusterIssuer
    name: cloudflare
