apiVersion: v1
kind: Secret
metadata:
  name: k10-cluster-passphrase
  namespace: kasten-io
stringData:
  vaulttransitkeyname: kasten
  vaulttransitpath: ${VAULT_TRANSIT_PATH}
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-creds
  namespace: kasten-io
stringData:
  vault_token: ${VAULT_TOKEN}
